In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
import warnings
import tensorflow_datasets as tfds
import tensorflow as tf
warnings.filterwarnings("ignore")

In [2]:
data_white, info_white = tfds.load(name="wine_quality/white",  split='train', with_info=True)

WARNING:absl:You use TensorFlow DType <dtype: 'float32'> in tfds.features This will soon be deprecated in favor of NumPy DTypes. In the meantime it was converted to float32.
WARNING:absl:You use TensorFlow DType <dtype: 'float64'> in tfds.features This will soon be deprecated in favor of NumPy DTypes. In the meantime it was converted to float64.

In [3]:
data_red, info_red = tfds.load(name="wine_quality/red", split='train', with_info=True)

In [4]:

df_red = tfds.as_dataframe(data_red, info_red)
df_white= tfds.as_dataframe(data_white, info_white)

In [5]:
name1 = 'red'
name2 = 'white'
df_red['type'] =name1
df_white['type'] = name2

df_wine = pd.concat([df_red, df_white], ignore_index=True)

df_wine

,features/alcohol,features/chlorides,features/citric acid,features/density,features/fixed acidity,features/free sulfur dioxide,features/pH,features/residual sugar,features/sulphates,features/total sulfur dioxide,features/volatile acidity,quality,type
0,10.55,0.050,0.06,0.99236,6.0,38.0,3.30,1.800000,0.50,89.0,0.54,6,red
1,11.60,0.086,0.31,1.00020,8.7,23.0,3.48,3.000000,0.74,81.0,0.69,6,red
2,11.70,0.012,0.28,0.99064,6.7,36.0,3.26,2.400000,0.39,100.0,0.28,7,red
3,9.50,0.078,0.24,0.99830,7.5,10.0,3.45,2.000000,0.78,28.0,0.55,6,red
4,9.20,0.088,0.26,0.99810,7.8,23.0,3.41,2.000000,0.74,48.0,0.54,6,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,11.30,0.051,0.44,0.99058,6.4,39.0,3.11,1.200000,0.75,122.0,0.16,7,white
6493,10.80,0.050,0.27,0.99476,6.1,51.0,3.22,11.500000,0.37,133.0,0.24,6,white
6494,8.70,0.051,0.59,0.99886,8.1,60.0,2.96,13.600000,0.39,134.0,0.36,5,white
6495,10.60,0.031,0.28,1.00295,6.8,27.0,3.06,26.049999,0.42,122.0,0.45,6,white
6496,12.80,0.029,0.28,0.99054,6.6,12.0,3.19,6.100000,0.27,93.0,0.36,7,white

In [6]:
df_wine.to_csv('wine.csv')